<?php

namespace ridesoft\MySqlConnectionBundle\common;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-07-18 at 12:56:23.
 */
class DBRepositoryTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var DBRepository
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new DBRepository;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers ridesoft\MySqlConnectionBundle\common\DBRepository::Inizialize
     * @todo   Implement testInizialize().
     */
    public function testInizialize() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ridesoft\MySqlConnectionBundle\common\DBRepository::getConnection
     * @todo   Implement testGetConnection().
     */
    public function testGetConnection() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ridesoft\MySqlConnectionBundle\common\DBRepository::select
     * @todo   Implement testSelect().
     */
    public function testSelect() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ridesoft\MySqlConnectionBundle\common\DBRepository::Insert
     * @todo   Implement testInsert().
     */
    public function testInsert() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ridesoft\MySqlConnectionBundle\common\DBRepository::Update
     * @todo   Implement testUpdate().
     */
    public function testUpdate() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ridesoft\MySqlConnectionBundle\common\DBRepository::dumpDb
     * @todo   Implement testDumpDb().
     */
    public function testDumpDb() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
