<?php

namespace ridesoft\MySqlConnectionBundle\common;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-07-18 at 12:56:23.
 */
class MySqlConnectionTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var MySqlConnection
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new MySqlConnection;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers ridesoft\MySqlConnectionBundle\common\MySqlConnection::__sleep
     * @todo   Implement test__sleep().
     */
    public function test__sleep() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ridesoft\MySqlConnectionBundle\common\MySqlConnection::__wakeup
     * @todo   Implement test__wakeup().
     */
    public function test__wakeup() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ridesoft\MySqlConnectionBundle\common\MySqlConnection::__clone
     * @todo   Implement test__clone().
     */
    public function test__clone() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ridesoft\MySqlConnectionBundle\common\MySqlConnection::close
     * @todo   Implement testClose().
     */
    public function testClose() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ridesoft\MySqlConnectionBundle\common\MySqlConnection::exeSQL
     * @todo   Implement testExeSQL().
     */
    public function testExeSQL() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ridesoft\MySqlConnectionBundle\common\MySqlConnection::beginTransaction
     * @todo   Implement testBeginTransaction().
     */
    public function testBeginTransaction() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ridesoft\MySqlConnectionBundle\common\MySqlConnection::CommitTransaction
     * @todo   Implement testCommitTransaction().
     */
    public function testCommitTransaction() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ridesoft\MySqlConnectionBundle\common\MySqlConnection::RollBackTransaction
     * @todo   Implement testRollBackTransaction().
     */
    public function testRollBackTransaction() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ridesoft\MySqlConnectionBundle\common\MySqlConnection::getResult
     * @todo   Implement testGetResult().
     */
    public function testGetResult() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ridesoft\MySqlConnectionBundle\common\MySqlConnection::getNumFields
     * @todo   Implement testGetNumFields().
     */
    public function testGetNumFields() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ridesoft\MySqlConnectionBundle\common\MySqlConnection::cleanField
     * @todo   Implement testCleanField().
     */
    public function testCleanField() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ridesoft\MySqlConnectionBundle\common\MySqlConnection::LogError
     * @todo   Implement testLogError().
     */
    public function testLogError() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
